### ISSUE TITLE
Windows 10 and Chrome 48

### ISSUE THREAD

**Issue by Gouigouix** [klesta490/bobril-clouseau#1]
Hello,

I installed the plugin but the panel does not appear in Chrome!
I'm on Windows 10 and Chrome: Version 48.0.2564.109 m (64-bit)

Thank you

**Comment by Bobris** [comment]
It does not have its own main panel. You need to focus some element and then you will see tab which does show more information about BobrilNode - its ctx and data ...

**Comment by klesta490** [comment]
Well, are you sure it's not there?
[Step1](http://i.imgur.com/YShB5OK.png)
[Step2](http://i.imgur.com/LbqL5Am.png)
[Step3](http://i.imgur.com/SX0lVVX.png)

**Comment by Gouigouix** [comment]
Yes,

I was looking in the main panel "Elements, Console ..."
I had not seen it displayed with that of "Styles, Event ..."

Thank you
